### ISSUE TITLE
Oscillate button turns on "run dry” mode

### ISSUE THREAD

**Issue by CooperCGN** [hassbian-ABC/homebridge-MiHumidifier#3]
Hello,

first thank you very much for this awesome plugin, the only one that actually seems to work with the ca1 type without problems. Although I must say that at first I was hesitating to install it because I had no idea what the screenshots were about, as I have no idea of Chinese ;)

One Question though remains. On my devices there is the "oscillating"-button visible (see attached screen shot) and if I use it my CA1 beeps but I have no idea what it actually does.

![IMG_0020](https://user-images.githubusercontent.com/29116509/58305958-20607880-7dfa-11e9-8a0e-ab57ffab28ea.png)

**Comment by DJay-X** [comment]
@hassbian-ABC 
Also thanks from my side for your great work and sharing with us.
The Plugin works perfect with my new [Xiaomi Smartmi Evapurative Humidifier zhimi-humidifier.ca1](https://de.aliexpress.com/item/32838120292.html)
Also looks great in [Eve HomeKit App](https://apps.apple.com/de/app/eve-für-homekit/id917695792).
![Napkin 2 19 07 19, 4 24 34 PM](https://user-images.githubusercontent.com/3874239/61544301-74c45500-aa45-11e9-8988-2647fec23a6e.png)

But I also was wondering what and if the Oscillate (Screenshot "Schwenken") is doing because the device beeps. 
Also the Status "Auto" in the App, does not trigger Auto on the device. When I set Fan Speed to 25% then the devices switches to Auto. 
Maybe you have some suggestions, update for Q&A or maybe an inspiration for one of the next updates of your plugin. 😉

However, thanks again for your time and great work.
All the best to you. 👍🏻

**Comment by CooperCGN** [comment]
@DJay-X
Meanwhile I found out that it activates the „run dry“ mode. That means after water tank it’s empty it runs for another eight hours so there won’t be any water left that might cause odor.

**Comment by DJay-X** [comment]
@CooperCGN 
Awesome. Good to know. Thx for this info. 
If you don't mind, maybe you can change the topic here to something like "Oscillate button turns on "run dry mode" and then close this "issue".  I'm sure this will help also others in the future. 
Thanks again. See you in the German forum.smartapfel.de 😀
